package com.policypulse.domain;

public enum Persona {
    TRADE_AND_SMALL_BUSINESS,
    INDUSTRY_AND_LOGISTICS,
    FINANCE_AND_PROFESSIONAL,
    PUBLIC_AND_COMMUNITY,
    STUDENT_AND_EDUCATOR,
    GENERAL_CITIZEN
}
